name: Frigate NVR (Full Access)
version: 0.15.2-Korvringen
slug: frigate_full_access
description: NVR with realtime local object detection for IP cameras
url: https://github.com/blakeblackshear/frigate-hass-addons
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
image: ghcr.io/blakeblackshear/frigate:0.15.2
panel_icon: "mdi:cctv"
panel_title: Frigate
